START TRANSACTION;

DROP SCHEMA IF EXISTS db_equipe2;
CREATE SCHEMA IF NOT EXISTS db_equipe2;
USE db_equipe2;

CREATE TABLE Programador(
    ID_PROGRAMADOR INT AUTO_INCREMENT,
    NOME_PROGRAMADOR VARCHAR(50),
    GENERO_PROGRAMADOR CHAR(1),
    DATA_NASC_PROGRAMADOR DATE,
    PRIMARY KEY (ID_PROGRAMADOR)
);

CREATE TABLE Startup(
    ID_STARTUP INT AUTO_INCREMENT,
    NOME_STARTUP VARCHAR(30),
    PRIMARY KEY (ID_STARTUP)
);


COMMIT;